---
- name: Check target systems prerequisists
  hosts: xpaste
  become: true
  tags: asserts # for debug propose
  tasks:
    - name: Test if target operating eviroment CentOS 7
      delegate_to: localhost
      ansible.builtin.assert:
        quiet: true
        that:
          - ansible_distribution == "CentOS"
          - ansible_distribution_major_version | int == 7

- name: Deploy nginx core
  hosts: xpaste
  become: true
  tags: nginx # for debug propose
  roles:
    - nginxinc.nginx

- name: Deploy postgresql
  hosts: xpaste
  become: true
  vars:
    postgresql_service_state: "started"
    postgresql_service_enabled: true
    postgresql_users:
      - name: "{{ xpaste_db_user }}"
        password: "{{ xpaste_db_password }}"
        encrypted: true
        db: "{{ xpaste_db_name }}"
        state: "present"
    postgresql_databases:
      - name: "{{ xpaste_db_name }}"
        owner: "{{ xpaste_db_user }}"
        state: "present"
  tags: postgresql # for debug propose
  roles:
    - slurm_postgresql
