---
- name: Check target systems prerequisists
  hosts: xpaste
  become: true
  tags: asserts # for debug propose
  tasks:
    - name: Test if target operating eviroment CentOS 7
      delegate_to: localhost
      ansible.builtin.assert:
        quiet: true
        that:
          - ansible_distribution == "CentOS"
          - ansible_distribution_major_version | int == 7

- name: Deploy nginx core
  hosts: xpaste
  become: true
  tags: nginx # for debug propose
  roles:
    - nginxinc.nginx

- name: Deploy postgresql
  hosts: xpaste
  become: true
  roles:
    - role: slurm.postgresql
      vars:
        postgresql_service_state: "started"
        postgresql_service_enabled: true
        postgresql_users:
          - name: "{{ app_xpaste_db_user }}"
            password: "{{ app_xpaste_db_password }}"
            encrypted: true
            db: "{{ app_xpaste_db_name }}"
            state: "present"
        postgresql_databases:
          - name: "{{ app_xpaste_db_name }}"
            owner: "{{ app_xpaste_db_user }}"
            state: "present"

- name: Deploy application
  hosts: xpaste
  become: true
  roles:
    - role: slurm.xpaste
      vars:
        xpaste_code_src: "{{ app_xpaste_code_src }}"
        xpaste_secret_key_base: "{{ app_xpaste_secret_key_base }}"
        xpaste_rail_env: "{{ app_xpaste_rail_env }}"
        xpaste_db_host: "{{ app_xpaste_db_host }}"
        xpaste_db_port: "{{ app_xpaste_db_port }}"
        xpaste_db_name: "{{ app_xpaste_db_name }}"
        xpaste_db_user: "{{ app_xpaste_db_user }}"
        xpaste_db_password: "{{ app_xpaste_db_password }}"
        xpaste_socket: "{{ app_xpaste_socket }}"
