---

- name: Test if operating eviroment suitable for role
  ansible.builtin.assert:
    quiet: true
    that:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version | int == 7
